"""User model

Revision ID: 14ecf012e638
Revises:
Create Date: 2024-06-04 08:30:52.771482

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "14ecf012e638"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone", sa.String(length=15), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("ADMIN", "USER", name="user_role"),
            nullable=False,
        ),
        sa.Column(
            "priority",
            postgresql.ENUM("LOW", "MEDIUM", "HIGH", name="user_priority"),
            nullable=False,
        ),
        sa.Column("receive_newsletters", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(
        op.f("ix_user_full_name"), "user", ["full_name"], unique=False
    )
    op.create_index(
        op.f("ix_user_is_active"), "user", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_user_phone"), "user", ["phone"], unique=False)
    op.create_index(
        op.f("ix_user_priority"), "user", ["priority"], unique=False
    )
    op.create_index(
        op.f("ix_user_receive_newsletters"),
        "user",
        ["receive_newsletters"],
        unique=False,
    )
    op.create_index(op.f("ix_user_role"), "user", ["role"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_role"), table_name="user")
    op.drop_index(op.f("ix_user_receive_newsletters"), table_name="user")
    op.drop_index(op.f("ix_user_priority"), table_name="user")
    op.drop_index(op.f("ix_user_phone"), table_name="user")
    op.drop_index(op.f("ix_user_is_active"), table_name="user")
    op.drop_index(op.f("ix_user_full_name"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # we need to drop the ENUM types as well
    op.execute("DROP TYPE user_priority")
    op.execute("DROP TYPE user_role")
    # ### end Alembic commands ###
