"""Category model priority column

Revision ID: 247c6e527d21
Revises: a24ef4d8936a
Create Date: 2024-10-08 12:37:51.402233

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "247c6e527d21"
down_revision: Union[str, None] = "a24ef4d8936a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "category", sa.Column("priority", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("category", "priority")
    # ### end Alembic commands ###
