"""Product Photo model is_main column

Revision ID: 58f58d3ab63d
Revises: 8801290da751
Create Date: 2024-07-20 14:20:49.158914

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "58f58d3ab63d"
down_revision: Union[str, None] = "8801290da751"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_photo", sa.Column("is_main", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_photo", "is_main")
    # ### end Alembic commands ###
