"""Some product columns now can be null

Revision ID: 75f8d3a3fc7c
Revises: 6ca767716ce5
Create Date: 2024-09-26 10:50:36.193344

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75f8d3a3fc7c"
down_revision: Union[str, None] = "6ca767716ce5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product", "have_glass", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "product", "material_choice", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "product",
        "type_of_platband_choice",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "product",
        "orientation_choice",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product",
        "orientation_choice",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "product",
        "type_of_platband_choice",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "product",
        "material_choice",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "product", "have_glass", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###
