"""Product model photo column

Revision ID: 7cf13775a55c
Revises: 8c2955d2ba3a
Create Date: 2024-06-12 19:05:48.623037

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7cf13775a55c"
down_revision: Union[str, None] = "8c2955d2ba3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("photo", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "photo")
    # ### end Alembic commands ###
