"""Product Photo model remove glass_color_id column

Revision ID: 80e471d5edda
Revises: 58f58d3ab63d
Create Date: 2024-07-25 12:01:11.040660

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80e471d5edda"
down_revision: Union[str, None] = "58f58d3ab63d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_product_photo_glass_color_id", table_name="product_photo"
    )
    op.drop_constraint(
        "product_photo_glass_color_id_fkey",
        "product_photo",
        type_="foreignkey",
    )
    op.drop_column("product_photo", "glass_color_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_photo",
        sa.Column(
            "glass_color_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "product_photo_glass_color_id_fkey",
        "product_photo",
        "product_glass_color",
        ["glass_color_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    op.create_index(
        "ix_product_photo_glass_color_id",
        "product_photo",
        ["glass_color_id"],
        unique=False,
    )
    # ### end Alembic commands ###
