"""Category and Size association CASCADE ForeignKey options

Revision ID: 86a8807b31ed
Revises: f0911a7ca150
Create Date: 2024-07-15 14:56:00.432423

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86a8807b31ed"
down_revision: Union[str, None] = "f0911a7ca150"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "category_size_association_product_size_id_fkey",
        "category_size_association",
        type_="foreignkey",
    )
    op.drop_constraint(
        "category_size_association_category_id_fkey",
        "category_size_association",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "category_size_association",
        "category",
        ["category_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "category_size_association",
        "product_size",
        ["product_size_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "category_size_association", type_="foreignkey")
    op.drop_constraint(None, "category_size_association", type_="foreignkey")
    op.create_foreign_key(
        "category_size_association_category_id_fkey",
        "category_size_association",
        "category",
        ["category_id"],
        ["id"],
    )
    op.create_foreign_key(
        "category_size_association_product_size_id_fkey",
        "category_size_association",
        "product_size",
        ["product_size_id"],
        ["id"],
    )
    # ### end Alembic commands ###
