"""Order and OrderItem models

Revision ID: 8bd9ee3694a9
Revises: 324dbe1f7974
Create Date: 2024-08-21 21:42:36.991515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8bd9ee3694a9"
down_revision: Union[str, None] = "324dbe1f7974"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("city_or_settlement", sa.String(), nullable=False),
        sa.Column("warehouse", sa.String(), nullable=True),
        sa.Column("delivery_address", sa.String(), nullable=True),
        sa.Column("additional_info", sa.String(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "NEW",
                "ACCEPTED",
                "READY_FOR_SHIPMENT",
                name="order_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_user_id"), "order", ["user_id"], unique=False
    )
    op.create_table(
        "order_item",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("color_id", sa.Integer(), nullable=True),
        sa.Column("size_id", sa.Integer(), nullable=True),
        sa.Column("covering_id", sa.Integer(), nullable=True),
        sa.Column("glass_color_id", sa.Integer(), nullable=True),
        sa.Column(
            "material",
            postgresql.ENUM(
                "WOOD",
                "MDF",
                name="item_material_enum",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "type_of_platband",
            postgresql.ENUM(
                "DEFAULT",
                "L_SHAPED",
                name="product_type_of_platband_enum",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "orientation",
            postgresql.ENUM(
                "LEFT",
                "RIGHT",
                name="product_orientation_enum",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("with_glass", sa.Boolean(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["color_id"],
            ["product_color.id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["covering_id"],
            ["product_covering.id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["glass_color_id"],
            ["product_glass_color.id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["order.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["size_id"],
            ["product_size.id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_item_color_id"),
        "order_item",
        ["color_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_item_covering_id"),
        "order_item",
        ["covering_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_item_glass_color_id"),
        "order_item",
        ["glass_color_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_item_order_id"),
        "order_item",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_item_product_id"),
        "order_item",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_item_size_id"), "order_item", ["size_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_item_size_id"), table_name="order_item")
    op.drop_index(op.f("ix_order_item_product_id"), table_name="order_item")
    op.drop_index(op.f("ix_order_item_order_id"), table_name="order_item")
    op.drop_index(
        op.f("ix_order_item_glass_color_id"), table_name="order_item"
    )
    op.drop_index(op.f("ix_order_item_covering_id"), table_name="order_item")
    op.drop_index(op.f("ix_order_item_color_id"), table_name="order_item")
    op.drop_table("order_item")
    op.drop_index(op.f("ix_order_user_id"), table_name="order")
    op.drop_table("order")
    # ### end Alembic commands ###
