"""Auth Token model

Revision ID: cbe214c24453
Revises: 7d5c1e91a7be
Create Date: 2024-08-02 12:09:39.044343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbe214c24453'
down_revision: Union[str, None] = '7d5c1e91a7be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_token',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('owner_email', sa.String(), nullable=False),
    sa.Column('token_type', postgresql.ENUM('REGISTRATION_CONFIRM', 'PASSWORD_RESET', 'EMAIL_CHANGE_CONFIRM', name='auth_token_type'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), server_default=sa.text("NOW() + INTERVAL '1 day'"), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_token_owner_email'), 'auth_token', ['owner_email'], unique=False)
    op.create_index(op.f('ix_auth_token_token'), 'auth_token', ['token'], unique=True)
    op.create_index(op.f('ix_auth_token_token_type'), 'auth_token', ['token_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_token_token_type'), table_name='auth_token')
    op.drop_index(op.f('ix_auth_token_token'), table_name='auth_token')
    op.drop_index(op.f('ix_auth_token_owner_email'), table_name='auth_token')
    op.drop_table('auth_token')
    # ### end Alembic commands ###
