"""Product model name column

Revision ID: e8e941fc8a42
Revises: 75f8d3a3fc7c
Create Date: 2024-10-02 10:06:39.085138

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8e941fc8a42"
down_revision: Union[str, None] = "75f8d3a3fc7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("name", sa.String(), nullable=True))
    op.create_index(op.f("ix_product_name"), "product", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_name"), table_name="product")
    op.drop_column("product", "name")
    # ### end Alembic commands ###
