"""Product photo

Revision ID: f0911a7ca150
Revises: 83325e4a05ea
Create Date: 2024-07-12 22:52:35.860257

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f0911a7ca150"
down_revision: Union[str, None] = "83325e4a05ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_photo",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("photo", sa.String(), nullable=False),
        sa.Column(
            "dependency",
            postgresql.ENUM(
                "COLOR",
                "GLASS_AVAILABILITY",
                "ORIENTATION",
                "SIZE",
                "TYPE_OF_PLATBAND",
                name="product_photo_dep_enum",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_photo_product_id"),
        "product_photo",
        ["product_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_product_photo_product_id"), table_name="product_photo"
    )
    op.drop_table("product_photo")
    # ### end Alembic commands ###
