export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const REM_NOTIFICATION = "REM_NOTIFICATION";
export const SET_CART_PRODUCTS = "SET_CART_PRODUCTS";
export const REM_CART_PRODUCT = "REM_CART_PRODUCT";
export const CHANGE_CART_PRODUCT = "CHANGE_CART_PRODUCT";
