services:
  postgresql:
    image: "postgres:15"
    restart: always
    container_name: "postgresql"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: "app"
    hostname: "relict_arte"
    depends_on:
      - postgresql
    environment:
      MODE: "PROD"
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    env_file:
      - .env.prod
    expose:
      - ${APP_PORT}
    volumes:
      - .:/app/api

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    restart: always
    ports:
      - "5672:${RABBITMQ_PORT}"
      - "15672:${RABBITMQ_PORT_SECOND}"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    env_file:
      - .env.prod

  celery:
    build:
      context: .
    container_name: "celery"
    command: /bin/sh -c /app/celery.sh
    depends_on:
      - rabbitmq
    environment:
      MODE: "PROD"
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    env_file:
      - .env.prod
    volumes:
      - .:/app/api

  nginx:
    image: nginx:latest
    build:
      context: ./nginx
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    env_file:
      - .env.prod
    depends_on:
      - app
    volumes:
      - ./nginx/templates:/etc/nginx/templates

  redis:
    image: "redis:latest"
    container_name: "redis"
    restart: always
    ports:
      - "6379:${REDIS_PORT}"
    env_file:
      - .env.prod

volumes:
  postgres_data: